### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by davidteal** [swayok/alternative-laravel-cache#8] opened 2019-04-08 16:19 UTC
Hi there.

Thanks for this library, it does exactly how I expected the default functionality to work. I'm having some issues with Laravel 5.8 though, as the cache TTL has changed from minutes to seconds.

See https://laravel.com/docs/5.8/releases#laravel-5.8 under PSR-16 Cache Compliance.

Are there any plans for an update?

Thanks.

**Comment by swayok** [comment] 2019-04-08 17:11
Hi. I'm planning to deliver an update this week. I've just started a new project with Laravel 5.8 and probably will face this issue soon.

**Comment by swayok** [comment] 2019-04-16 14:07
@davidteal
This is just a coincidence but I've finished update for Laravel 5.8 several minutes ago =) 
Also I've fixed that incompatibility in `putMany` you mentioned.
Unfortunately I cannot test it right now because I'm on a starting stage of my new project.

**Comment by davidteal** [comment] 2019-04-16 14:39
@swayok Great stuff. I'll update and will post here if I spot any issues.

Thanks.

**Comment by gmoigneu** [comment] 2019-05-08 07:01
I can confirm this is working as expected on 5.8.16 Thanks!

**Comment by swayok** [comment] 2019-05-08 08:53
@gmoigneu Thank you for confirmation. Then I'm closing the issue.

**Closed by swayok** 2019-05-08 08:53 UTC
Labels: enhancement
